// <auto-generated />
using System;
using DAL.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20230207170841_migracion-dwh")]
    partial class migraciondwh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.EstadoPedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Cod_estado_devolucion")
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Cod_estado_devolucion");

                    b.Property<string>("Cod_estado_envio")
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Cod_estado_envio");

                    b.Property<string>("Cod_estado_pago")
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Cod_estado_pago");

                    b.Property<string>("Cod_linea")
                        .HasColumnType("character varying(11)")
                        .HasColumnName("Cod_linea");

                    b.Property<string>("Cod_pedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Cod_pedido");

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Md_uuid");

                    b.HasKey("Id");

                    b.HasIndex("Cod_estado_devolucion");

                    b.HasIndex("Cod_estado_envio");

                    b.HasIndex("Cod_estado_pago");

                    b.HasIndex("Cod_linea");

                    b.ToTable("Tdc_tch_estado_pedidos", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Entities.EstadosDevolucionPedido", b =>
                {
                    b.Property<string>("Cod_estado_devolucion")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Cod_estado_devolucion");

                    b.Property<string>("Des_estado_devolucion")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("Des_estado_devolucion");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Md_uuid");

                    b.HasKey("Cod_estado_devolucion");

                    b.ToTable("Tdc_cat_estados_devolucion_pedido", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Entities.EstadosEnvioPedido", b =>
                {
                    b.Property<string>("Cod_estado_envio")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Cod_estado_envio");

                    b.Property<string>("Des_estado_envio")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("Des_estado_envio");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Md_uuid");

                    b.HasKey("Cod_estado_envio");

                    b.ToTable("Tdc_cat_estados_envio_pedido", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Entities.EstadosPagoPedido", b =>
                {
                    b.Property<string>("Cod_estado_pago")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Cod_estado_pago");

                    b.Property<string>("Des_estado_pago")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Des_estado_pago");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Md_uuid");

                    b.HasKey("Cod_estado_pago");

                    b.ToTable("Tdc_cat_estados_pago_pedido", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Entities.LineasDistribucion", b =>
                {
                    b.Property<string>("Cod_linea")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("Cod_linea");

                    b.Property<string>("Cod_barrio")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Cod_barrio");

                    b.Property<string>("Cod_municipio")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Cod_municipio");

                    b.Property<string>("Cod_provincia")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Cod_provincia");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Md_date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<Guid>("Md_uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Md_uuid");

                    b.HasKey("Cod_linea");

                    b.ToTable("Tdc_cat_lineas_distribucion", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Entities.EstadoPedidos", b =>
                {
                    b.HasOne("DAL.Entities.EstadosDevolucionPedido", "EstadoDevolucion")
                        .WithMany("ListaEstadoPedidos")
                        .HasForeignKey("Cod_estado_devolucion");

                    b.HasOne("DAL.Entities.EstadosEnvioPedido", "EstadoEnvio")
                        .WithMany("ListaEstadoPedidos")
                        .HasForeignKey("Cod_estado_envio");

                    b.HasOne("DAL.Entities.EstadosPagoPedido", "EstadoPago")
                        .WithMany("ListaEstadoPedidos")
                        .HasForeignKey("Cod_estado_pago");

                    b.HasOne("DAL.Entities.LineasDistribucion", "LineaDistribucion")
                        .WithMany("ListaEstadoPedidos")
                        .HasForeignKey("Cod_linea");

                    b.Navigation("EstadoDevolucion");

                    b.Navigation("EstadoEnvio");

                    b.Navigation("EstadoPago");

                    b.Navigation("LineaDistribucion");
                });

            modelBuilder.Entity("DAL.Entities.EstadosDevolucionPedido", b =>
                {
                    b.Navigation("ListaEstadoPedidos");
                });

            modelBuilder.Entity("DAL.Entities.EstadosEnvioPedido", b =>
                {
                    b.Navigation("ListaEstadoPedidos");
                });

            modelBuilder.Entity("DAL.Entities.EstadosPagoPedido", b =>
                {
                    b.Navigation("ListaEstadoPedidos");
                });

            modelBuilder.Entity("DAL.Entities.LineasDistribucion", b =>
                {
                    b.Navigation("ListaEstadoPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
